export const country = {
  Afghanistan: [
    "Herat",
    "Kabul",
    "Kandahar",
    "Molah",
    "Rana",
    "Shar",
    "Sharif",
    "Wazir Akbar Khan",
  ],
  Albania: [
    "Elbasan",
    "Petran",
    "Pogradec",
    "Shkoder",
    "Tirana",
    "Ura Vajgurore",
  ],
  Bangladesh: [
    "Agrabad",
    "Bangla",
    "Barisal",
    "Bazar",
    "Chittagong",
    "Comilla",
    "Delta",
    "Dhaka",
    "Hossain",
    "Jessore",
    "Kabi",
    "Kazipur",
    "Mymensingh",
    "Narayanganj",
    "Rajshahi",
    "Tejgaon",
    "Uttara",
  ],
  "United Arab Emirates": [
    "Abu Dhabi",
    "Al Ain",
    "Al Khan",
    "Ar Ruways",
    "As Satwah",
    "Dayrah",
    "Dubai",
    "Fujairah",
    "Ras al-Khaimah",
    "Sharjah",
  ],
  Zimbabwe: [
    "Bulawayo",
    "Chinhoyi",
    "Greendale",
    "Gwanda",
    "Harare",
    "Kwekwe",
    "Mufakose",
    "Mutare",
    "Victoria Falls",
  ],
};
